=== bogeo/sl-geovislab/xsd/plml-bo-2.2.xsd
<?xml version="1.0" ?>
<!--- PLML extended version BO-2.2 from https://github.com/bogeo/sl-geovislab/etc/plml_bo-2.2.xsd. --> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="pattern">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="name-DE" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="alias" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="alias-DE" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="illustration" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="problem" type="xsd:string" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="problem-DE" type="xsd:string" minOccurs="0 " maxOccurs="1"/>
				<xsd:element name="context" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="forces" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="solution" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="synopsis" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="diagram" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="location" type="xsd:string" use="required"/>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="evidence" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="example" minOccurs="0" maxOccurs="unbounded"/>
							<xsd:element name="rationale" minOccurs="0" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="confidence" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:annotation>
								<xsd:documentation>Special rating type as PLML extension</xsd:documentation>
							</xsd:annotation>
							<xsd:extension base="rating"/>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="literature" minOccurs="0" maxOccurs="1">
					<xsd:annotation>
						<xsd:documentation>As in Bienhaus's PLMLx, literature will be given separate child elements here</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="bibliomixed" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="id" type="xsd:string" use="optional"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="implementation" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="formalization" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="participant" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>Optional listing of pattern participants</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="identifier" type="xsd:string" use="required"/>
											<xsd:attribute name="type" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="source-code" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="location" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="language" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="related-patterns" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="pattern-link" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>Pre-defined PLML relation type</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="type" type="relation" use="required"/>
											<xsd:attribute name="patternID" type="xsd:integer" use="required"/>
											<xsd:attribute name="collection" type="xsd:string" use="required"/>
											<xsd:attribute name="label" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="management" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="author" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="revision-number" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="creation-date" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="last-modified" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="credits" type="xsd:string" minOccurs="0" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="patternID" type="xsd:integer"/>
			<xsd:attribute name="collection" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="ratingAlexandrian">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="-"/>
			<xsd:enumeration value="*"/>
			<xsd:enumeration value="**"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ratingAltern">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Idea"/>
			<xsd:enumeration value="reviewed"/>
			<xsd:enumeration value="timeless"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="rating">
		<xsd:union memberTypes="ratingAlexandrian ratingAltern"/>
	</xsd:simpleType>
	<xsd:simpleType name="relationPLML">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-a"/>
			<xsd:enumeration value="is-contained-by"/>
			<xsd:enumeration value="contains"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relationHenzen">
		<xsd:annotation>
			<xsd:documentation>Additional relations as defined by Henzen</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-dependent-on"/>
			<xsd:enumeration value="is-alternative-to"/>
			<xsd:enumeration value="is-specialization-of"/>
			<xsd:enumeration value="is-related-to"/>
			<xsd:enumeration value="is-incompatible-to"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relationExt">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-equal-to"/>
			<xsd:enumeration value="uses"/>
			<xsd:enumeration value="is-supplement-to"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relation">
		<xsd:annotation>
			<xsd:documentation>Pattern relation types</xsd:documentation>
		</xsd:annotation>
		<xsd:union memberTypes="relationPLML relationHenzen relationExt"/>
	</xsd:simpleType>
</xsd:schema>

=== bogeo/sl-geovislab/patterns/FlashStatementControl.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="13" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Flash Statement Control</name>
  <name-DE>Blitzstatement-Steuerung</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Mehrere Studierende möchten sichzu einem Thema äußern, ungeordnete Wortbeiträge der Avatare
    sind jedoch schwer inhaltlich zu erfassen ("Durcheinandergerede").    
  </problem-DE>
  <solution>
    TODO
  </solution>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="participant" type="Avatar"/>
    <participant identifier="scheduler" type="Programme"/>
    <participant identifier="visualization" type="Programme"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/OverviewMap.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="14" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Overview Map</name>
  <name-DE>Übersichtskarte</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Durch die Augen des Avatars sind die sich in einem virtuellen Raum und der Umgebung aufhaltenden 
    Avatare schwer in ihrer Ganzheit zu erfassen.    
  </problem-DE>
  <solution>TODO engl. description</solution>
  <solution-DE>
    Es wird eine Übersichtskarte ("overview map") bereitgestellt, in welcher die Aufenthaltspositionen 
    anderer Avatare dargestellt sind.
  </solution-DE>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="viewpoint" type="Camera"/>
    <participant identifier="egoView" type="Camera"/>
    <participant identifier="roomView" type="Camera"/>
    <participant identifier="overviewMap" type="UIElement"/>
  </formalization>
  <related-patterns>
    <pattern-link type="is-related-to" patternID="6" collection="B" label="Distance View" ref="./Distance View.xml" />
  </related-patterns>
</pattern>

=== bogeo/sl-geovislab/patterns/Teleport.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="15" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Teleport</name>
  <name-DE>Teleporter</name-DE>
  <problem>TODO</problem>
  <solution>TODO</solution>
  <confidence>Idea</confidence>
  <literature>
    <bibliomixed id="1">
        Threesixty Reality Ltd., eds. (2023): Interaction design patterns : A collection of interaction patterns for virtual and 
        augmented reality. http://s824284416.websitehome.co.uk/interaction-design-patterns-library/virtual-reality/
    </bibliomixed>
  </literature>
  <formalization language="(none)">
    <participant identifier="avatar" type="Avatar"/>
    <participant identifier="target" type="GeoPosition"/>
    <participant identifier="teleporterObject" type="UIElement"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/TargetedMessage.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="15" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Targeted message</name>
  <name-DE>Gezielte Nachricht</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Sich wiederholende Hinweismeldungen stören häufig, indem z. B. Nutzer:innen ablenken 
    oder ermüden. Die Meldungen sollen somit auf das Nötige beschränkt werden, d. h. nur den 
    Nutzer:innen gegeben werden, die es in einer bestimmten Situation tatsächlich betrifft. 
    (U. U. ist hierbei auch gefordert, dass andere Nutzer:innen nicht erfahren, dass der Hinweis 
    gegeben wurde.)
  </problem-DE>
  <solution>TODO  engl. description</solution>
  <solution-DE>
    Basierend auf Kontextinformation über Nutzer:innen und deren Verhalten und Rückmeldungen 
    versendet eine Bot-Komponente die Hinweismeldungen gezielt. Beispiele für Kontextinformation:
    Jemand klickt ein Objekt erstmalig an, ein spezieller Fehler wird ausgelöst, die Historie
    der Nutzer:innenaktionen deutet darauf hin, dass eine Hinweis sinnvoll/nicht sinnvoll ist, 
    der/die Nutzer:in hat dem Bot Vorlieben mitgeteilt (z. B.: "Diese Nachricht nicht mehr
    anzeigen").  
  </solution-DE>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="avatar" type="Avatar"/>
    <participant identifier="context" type="ContextInfo"/>
    <participant identifier="bot" type="ProgramScript"/>
    <participant identifier="message" type="String"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/Shelf.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="8" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Shelf</name>
    <name-DE>Regal</name-DE>
    <problem>TODO engl. description</problem>
    <problem-DE>
        Ein/e Raumnutzer:in sucht ein bestimmtes Objekt (oder eine bestimmte Information) im Raum,
        weiß jedoch nicht, wo diese zu finden ist. Insbesondere bei eienr großen Zahl von Gegenständen
        ist es mitunter schwer, für alles einen geeigneten Platz zu finden.   
    </problem-DE>
    <solution>
        TODO
    </solution>
    <confidence>Idea</confidence>
    <formalization language="(none)">
        <participant identifier="shelf" type="VisualizationObject"/>
        <participant identifier="packaging" type="VisualizationObject"/>
        <participant identifier="content" type="Notecard"/>
    </formalization>
    <related-patterns>
        <pattern-link type="is-related-to" patternID="1" collection="A" label="Familiar Space Replication"/>
    </related-patterns>
</pattern>

=== bogeo/sl-geovislab/patterns/Seating.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="2" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Seating</name>
  <name-DE>Sitzgelegenheit</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Voreinstellungsgemäß werden Avatare zumeist in stehender Position dargestellt. Mitunter wirkt
    dies unnatürlich (z. B. sitzen die Teilnehmer:innen einer längeren realen Besprechung oder 
    Lehrveranstaltung üblicherweise). Daneben ist es Nutzer:innen oft unangenehm, wenn der zugehörige      
    Avatar unnatürlich und mitunter störend (z. B. anderen die Sicht versprerend) im virtuellen Raum
    "dumm" herumsteht. 
  </problem-DE>
  <solution>
    Den Avataren werden Sitzgelegenheiten, z. B. Stühle, Sitzkissen u. ä. angeboten, auf die sich 
    ein Avatar durch einen einfach Befehl setzen kann.    
  </solution>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="seat" type="VisObject"/>
    <participant identifier="avatarBehavior" type="AvatorAnimation"/>
    <participant identifier="control" type="UIElement"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/FlashStatementBot.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="13" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Flash Statement Bot</name>
  <name-DE>Blitzstatement-Bot</name-DE>
  <alias>Stand-up Meeting (Scrum)</alias>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Mehrere Studierende möchten sich zu einem Thema äußern, ungeordnete Wortbeiträge der Avatare
    sind jedoch schwer inhaltlich zu erfassen ("Durcheinandergerede").    
  </problem-DE>
  <solution>TODO engl. description</solution>
  <solution-DE>
    Ein freundlicher Bot registriert die Studierenden, die an der Rederunde teilnehmen möchten. 
    Sobald die Registrierung abgeschlossen ist, erteilt der Bot den Teilnehmer:innen für eine 
    voreingestellte Zeit persönlich das Wort und gibt Hinweise zur Zeiteinhaltung.
  </solution-DE>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="participant" type="Avatar"/>
    <participant identifier="scheduler" type="ProgramScript"/>
    <participant identifier="visualization" type="ProgramScript"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/EnvironmentalSpace.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="12" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Environmental Space</name>
  <name-DE>Umgebungsraum</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Ein/e Raumnutzer:in fühlt sich (psychologisch) eingeengt im Raum ("Platzangst").   
  </problem-DE>
  <solution>TODO engl. description</solution>
  <solution-DE>
    Um den virtuellen Lehrraum herum werden weitere, sich nahtlos anschließende Räume bereitgestellt, 
    in die sich ein Avatar bei Bedarf zurückziehen oder die er einsehen kann (z. B. mittels eines 
    Blicks aus dem Fenster). Belebend wirken dezente Ereignisse in der Außenwelt, z. B. dezente 
    Umgebungsgeräusche (Vögel, fernes Hupen u. ä.), andere Avatare als Passanten oder Bots etc.     
  </solution-DE>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="inside" type="GeoRegion"/>
    <participant identifier="outside" type="GeoRegion"/>
    <participant identifier="door" type="Widget"/>
    <participant identifier="window" type="VisualizationObject"/>
    <participant identifier="avatar" type="Avatar"/>
  </formalization>
</pattern>
