=== bogeo/sl-geovislab/xsd/plml-bo-2.2.xsd
<?xml version="1.0" ?>
<!--- PLML extended version BO-2.2 from https://github.com/bogeo/sl-geovislab/etc/plml_bo-2.2.xsd. --> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="pattern">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="name-DE" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="alias" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="alias-DE" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="illustration" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="problem" type="xsd:string" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="problem-DE" type="xsd:string" minOccurs="0 " maxOccurs="1"/>
				<xsd:element name="context" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="forces" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="solution" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="synopsis" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="diagram" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="location" type="xsd:string" use="required"/>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="evidence" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="example" minOccurs="0" maxOccurs="unbounded"/>
							<xsd:element name="rationale" minOccurs="0" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="confidence" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:annotation>
								<xsd:documentation>Special rating type as PLML extension</xsd:documentation>
							</xsd:annotation>
							<xsd:extension base="rating"/>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="literature" minOccurs="0" maxOccurs="1">
					<xsd:annotation>
						<xsd:documentation>As in Bienhaus's PLMLx, literature will be given separate child elements here</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="bibliomixed" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="id" type="xsd:string" use="optional"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="implementation" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="formalization" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="participant" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>Optional listing of pattern participants</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="identifier" type="xsd:string" use="required"/>
											<xsd:attribute name="type" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="source-code" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="location" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="language" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="related-patterns" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="pattern-link" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>Pre-defined PLML relation type</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="type" type="relation" use="required"/>
											<xsd:attribute name="patternID" type="xsd:integer" use="required"/>
											<xsd:attribute name="collection" type="xsd:string" use="required"/>
											<xsd:attribute name="label" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="management" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="author" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="revision-number" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="creation-date" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="last-modified" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="credits" type="xsd:string" minOccurs="0" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="patternID" type="xsd:integer"/>
			<xsd:attribute name="collection" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="ratingAlexandrian">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="-"/>
			<xsd:enumeration value="*"/>
			<xsd:enumeration value="**"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ratingAltern">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Idea"/>
			<xsd:enumeration value="reviewed"/>
			<xsd:enumeration value="timeless"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="rating">
		<xsd:union memberTypes="ratingAlexandrian ratingAltern"/>
	</xsd:simpleType>
	<xsd:simpleType name="relationPLML">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-a"/>
			<xsd:enumeration value="is-contained-by"/>
			<xsd:enumeration value="contains"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relationHenzen">
		<xsd:annotation>
			<xsd:documentation>Additional relations as defined by Henzen</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-dependent-on"/>
			<xsd:enumeration value="is-alternative-to"/>
			<xsd:enumeration value="is-specialization-of"/>
			<xsd:enumeration value="is-related-to"/>
			<xsd:enumeration value="is-incompatible-to"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relationExt">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-equal-to"/>
			<xsd:enumeration value="uses"/>
			<xsd:enumeration value="is-supplement-to"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relation">
		<xsd:annotation>
			<xsd:documentation>Pattern relation types</xsd:documentation>
		</xsd:annotation>
		<xsd:union memberTypes="relationPLML relationHenzen relationExt"/>
	</xsd:simpleType>
</xsd:schema>

=== bogeo/sl-geovislab/patterns/MultipleViewpoints.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="6" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Multiple Viewpoints</name>
    <name-DE>Mehrere Ansichtspunkte</name-DE>
    <problem>TODO engl. description</problem>
    <problem-DE>
        Durch die Augen des Avatars sind der virtuelle Raum und sich darin aufhaltenden Avatare schwer
        in ihrer GÃ¤nze zu erfassen.    
    </problem-DE>
    <solution>
        TODO
    </solution>
    <confidence>Idea</confidence>
    <formalization language="(none)">
        <participant identifier="viewpoint" type="Camera"/>
        <participant identifier="egoView" type="Camera"/>
        <participant identifier="roomView" type="Camera"/>
        <participant identifier="overviewMap" type="UIElement"/>
    </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/SpeedTrafficLights.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="7" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Speed Traffic Lights</name>
  <name-DE>Geschwindigkeitsampel</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Der/die Dozent:in redet zu schnell. Die Studierenden möchten gerne eine Rückmeldung geben, ohne 
    den/die Dozent:in im Redefluss allzu sehr zu stören und ohne ihre Identität (bzw. die ihres Avatars) 
    preiszugeben.      
  </problem-DE>
  <solution>TODO engl. description</solution>
  <solution-DE>
    Die Avatare können für den Dozenten bzw. die Dozentin unsichtbar einen Schalter anklicken, der 
    eine Ampelanzeige (oder eine Sound-Ausgabe) steuert, die bei Wünschen nach einer langsameren 
    Erläuterung oder nach einer Wiederholung auf Rot springt. Nach der Wiederholung setzt der 
    Dozent bzw. die Dozentin die Ampel wieder auf Grün zurück.     
  </solution-DE>
  <confidence>Idea</confidence>
  <formalization language="LSL">
    <participant identifier="reporter" type="Avatar"/>
    <participant identifier="report" type="SpeedValue"/>
    <participant identifier="controlLogic" type="Programm"/>
    <participant identifier="greenLight" type="ColoredCircle"/>
    <participant identifier="yellowLight" type="ColoredCircle"/>
    <participant identifier="redLight" type="ColoredCircle"/>
    <participant identifier="presenter" type="Avatar"/>
    <participant identifier="reset" type="Command"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/VisibleSpeaker.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="4" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Visible Speaker</name>
  <name-DE>Sichtbarer Sprecher</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Im Regelfall ist es erforderlich, dass eine Wortmeldung (z. B. ein natürlichsprachliches 
    Sprechen) dem jeweils sprechenden Avatar zugeordenbar ist. In Gesprächsgruppen mitm mehr als zwei 
    Teilnehmer:innen mag eine die Möglichkeit der Lippenbewegung eines sprechenden Avatars implementiert
    sein, und auch möglicherweise vorhandene 3D-Sound-Funktionen können die Sprecherortung unterstützen; 
    im Regelfall reicht dies jedoch auf Grund der schlechten Wahrnehmbarkeit nicht aus.     
  </problem-DE>
  <solution>
    TODO
  </solution>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="avatar" type="Avatar"/>
    <participant identifier="isTalking" type="Boolean"/>
    <participant identifier="visualization" type="Animation"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/DocumentDelivery.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="9" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Document Delivery</name>
  <name-DE>Dokumentenübergabe</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Der Studierende möchte Information aus dem virtuellen Lehrraum zum Zweck der Nachbereitung außerhalb
    der virtuellen Welt nutzen. Wie bekommt er Information aus dem Raum heraus?
  </problem-DE>
  <solution>
    TODO
  </solution>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="control" type="UIElement"/>
    <participant identifier="notecard" type="TextDocument"/>
    <participant identifier="reference" type="URI"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/AvatarGesture.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="5" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Avatar Gesture</name>
    <name-DE>Avatar-Geste</name-DE>
    <problem>TODO engl. description</problem>
    <problem-DE>
        Der Avatar soll schnell eine Reaktion zeigen, um eine flüssige Kommunikation mit anderen 
        Avataren zu ermöglichen. Eintippen aufwändiger Texte würde lange dauern (und zudem stören
        oft Schreibfehler).    
    </problem-DE>
    <solution>
        TODO
    </solution>
    <confidence>Idea</confidence>
    <formalization language="(none)">
        <participant identifier="avatar" type="Avatar"/>
        <participant identifier="control" type="UIElement"/>
        <participant identifier="gesturePool" type="Gesture"/>
        <participant identifier="gestureImpl" type="Animation"/>
    </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/Doorbell.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="11" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Doorbell</name>
  <name-DE>Türklingel</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Ein Studierender möchte sich bemerkbar machen, jedoch ist er aktuell nicht im Sichtfeld des 
    Lehrenden. 
  </problem-DE>
  <solution>
    TODO
  </solution>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="bell" type="InteractiveVisualzationObject"/>
    <participant identifier="ringtone" type="Sound"/>
    <participant identifier="soundPlayer" type="Programme"/>
    <participant identifier="message" type="Text"/>
  </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/DistanceView.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="6" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Distance View</name>
  <name-DE>Distanzansicht</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Durch die Augen des Avatars sind der virtuelle Raum und sich darin aufhaltenden Avatare schwer
    in ihrer Gesamtheit zu erfassen.    
  </problem-DE>
  <solution>TODO engl. description</solution>
  <solution-DE>
    Neben der Ego-Sicht durch die Augen des Avatars werden weitere Sichten bereitgestellt, z. B. aus 
    wenigen Metern Entfernung auf die Gesamtgruppe innerhalb eines Raums (Distanzansicht). Ergänzend 
    kann auch eine Übersichtskarte ("overview map") bereitgestellt werden, in welcher die Positionen 
    der Avatare dargestellt sind; siehe dazu separate Muster-Beschreibung.    
  </solution-DE>
  <confidence>Idea</confidence>
  <literature>
    <bibliomixed id="1">
        Pruett, C. (2017): Lessons from the Frontlines : Modern VR Design Patterns.
        https://developer.oculus.com/blog/lessons-from-the-frontlines-modern-vr-design-patterns
    </bibliomixed>
  </literature>
  <formalization language="(none)">
    <participant identifier="viewpoint" type="Camera"/>
    <participant identifier="egoView" type="Camera"/>
    <participant identifier="roomView" type="Camera"/>
    <participant identifier="overviewMap" type="UIElement"/>
  </formalization>
  <related-patterns>
    <pattern-link type="is-related-to" patternID="14" collection="B" label="Overview Map" ref="./OverViewMap.xml" />
  </related-patterns>
</pattern>

=== bogeo/sl-geovislab/patterns/FamiliarSpaceReplication.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="1" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Familiar Space Replication</name>
    <name-DE>Vertraute Raumnachbildung</name-DE>
    <problem>TODO engl. description</problem>
    <problem-DE>
        Ein/e Raumnutzer:in sucht ein bestimmtes Objekt (oder eine bestimmte Information) im Raum,
        wei√ü jedoch nicht, wo diese zu finden ist.   
    </problem-DE>
    <solution>
        TODO
    </solution>
    <confidence>Idea</confidence>
    <formalization language="(none)">
        <participant identifier="item" type="VisualizationObject"/>
        <participant identifier="position" type="GeoPosition"/>
        <participant identifier="space" type="GeoSpace"/>
    </formalization>
    <related-patterns>
        <pattern-link type="is-related-to" patternID="8" collection="A" label="Shelf" ref="./Shelf.xml"/>
    </related-patterns>
</pattern>
