=== bogeo/sl-geovislab/xsd/plml-bo-2.2.xsd
<?xml version="1.0" ?>
<!--- PLML extended version BO-2.2 from https://github.com/bogeo/sl-geovislab/etc/plml_bo-2.2.xsd. --> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="pattern">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="name-DE" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="alias" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="alias-DE" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="illustration" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="problem" type="xsd:string" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="problem-DE" type="xsd:string" minOccurs="0 " maxOccurs="1"/>
				<xsd:element name="context" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="forces" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="solution" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="synopsis" type="xsd:string" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="diagram" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="location" type="xsd:string" use="required"/>
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="evidence" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="example" minOccurs="0" maxOccurs="unbounded"/>
							<xsd:element name="rationale" minOccurs="0" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="confidence" minOccurs="1" maxOccurs="1">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:annotation>
								<xsd:documentation>Special rating type as PLML extension</xsd:documentation>
							</xsd:annotation>
							<xsd:extension base="rating"/>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="literature" minOccurs="0" maxOccurs="1">
					<xsd:annotation>
						<xsd:documentation>As in Bienhaus's PLMLx, literature will be given separate child elements here</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="bibliomixed" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="id" type="xsd:string" use="optional"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="implementation" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="formalization" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="participant" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>Optional listing of pattern participants</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="identifier" type="xsd:string" use="required"/>
											<xsd:attribute name="type" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="source-code" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="location" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="language" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="related-patterns" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="pattern-link" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>Pre-defined PLML relation type</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="type" type="relation" use="required"/>
											<xsd:attribute name="patternID" type="xsd:integer" use="required"/>
											<xsd:attribute name="collection" type="xsd:string" use="required"/>
											<xsd:attribute name="label" type="xsd:string" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="management" minOccurs="0" maxOccurs="1">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="author" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="revision-number" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="creation-date" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="last-modified" type="xsd:string" minOccurs="0" maxOccurs="1"/>
							<xsd:element name="credits" type="xsd:string" minOccurs="0" maxOccurs="1"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="patternID" type="xsd:integer"/>
			<xsd:attribute name="collection" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="ratingAlexandrian">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="-"/>
			<xsd:enumeration value="*"/>
			<xsd:enumeration value="**"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ratingAltern">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Idea"/>
			<xsd:enumeration value="reviewed"/>
			<xsd:enumeration value="timeless"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="rating">
		<xsd:union memberTypes="ratingAlexandrian ratingAltern"/>
	</xsd:simpleType>
	<xsd:simpleType name="relationPLML">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-a"/>
			<xsd:enumeration value="is-contained-by"/>
			<xsd:enumeration value="contains"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relationHenzen">
		<xsd:annotation>
			<xsd:documentation>Additional relations as defined by Henzen</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-dependent-on"/>
			<xsd:enumeration value="is-alternative-to"/>
			<xsd:enumeration value="is-specialization-of"/>
			<xsd:enumeration value="is-related-to"/>
			<xsd:enumeration value="is-incompatible-to"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relationExt">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="is-equal-to"/>
			<xsd:enumeration value="uses"/>
			<xsd:enumeration value="is-supplement-to"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="relation">
		<xsd:annotation>
			<xsd:documentation>Pattern relation types</xsd:documentation>
		</xsd:annotation>
		<xsd:union memberTypes="relationPLML relationHenzen relationExt"/>
	</xsd:simpleType>
</xsd:schema>

=== bogeo/sl-geovislab/patterns/IndividualSettings.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="10" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>Individuelle Settings</name>
    <name-DE>Individuelle Einstellungen</name-DE>
    <problem>TODO engl. description</problem>
    <problem-DE>
        Studierende haben unterschiedliche Skills in der Bedienung ihres Avatars.      
    </problem-DE>
    <solution>
        TODO
    </solution>
    <confidence>Idea</confidence>
    <formalization language="(none)">
        <participant identifier="settings" type="KeyValuePairList"/>
        <participant identifier="talkType" type="ConfigurationElement"/>
        <participant identifier="navigationType" type="ConfigurationElement"/>
    </formalization>
</pattern>

=== bogeo/sl-geovislab/patterns/ParametrizedAvatarAppearance.xml
<?xml-stylesheet href="../etc/plml_bo-2.2.css" type="text/css"?>
<pattern patternID="3" xsi:noNamespaceSchemaLocation="../xsd/plml-bo-2.2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>Parametrized Avatar Appearance</name>
  <name-DE>Parametrisierte Avatar-Gestalt</name-DE>
  <problem>TODO engl. description</problem>
  <problem-DE>
    Die Zuordnung eines Avatars zu vorherigen Wortbeiträgen oder Aktionen im virtuellen Lehrraum ist 
    nötig.       
  </problem-DE>
  <solution>TODO engl. description</solution>
  <solution-DE>
    Dies lässt sich durch eine individuelle Gestaltung der Avatare lösen, z. B. mittels Kleidung,
    Frisuren etc., die mittels individuell einstellbarer Parameter vorgehalten wird. Einfache Varianten
    beschränken sich auf Parameter wie Größe/Breite, Farbwahl u. ä. 
  </solution-DE>
  <confidence>Idea</confidence>
  <formalization language="(none)">
    <participant identifier="avatar" type="Avatar"/>
    <participant identifier="parameter" type="KeyValuePairList"/>
    <participant identifier="color" type="KeyValuePair"/>
    <participant identifier="geometricParameter" type="KeyValuePair"/>
  </formalization>
</pattern>
