=== bogeo/sl-geovislab/xsd/sl-object.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sl-object">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="creator">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="sl-id" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="commands" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="command" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="collection" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="purchase" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="slm-description" type="xs:string" minOccurs="0" maxOccurs="1"/>
              <xs:element name="slm-seller" type="xs:string" minOccurs="0" maxOccurs="1"/>
              <xs:element name="slm-price" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="primitives" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sl-prim" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="content" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sl-script" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="sl-notecard" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bogeo/sl-geovislab/inventory/objects/SurveyingDevice.xml
<sl-object xsi:noNamespaceSchemaLocation="../../xsd/sl-object.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Surveying Device</title>
    <creator>
        <name>Benno Schmidt</name>
        <sl-id>BennoSchmidt</sl-id>
    </creator>
    <commands>
        <command>/5 info</command>
        <command>/5 save</command>
        <command>/5 diff</command>
        <command>/5 poly</command>
        <command>/5 home</command>
        <command>/5 help</command>
    </commands>
    <collection>
        <item>Head</item>
        <item>Mounting Bar</item>
        <item>Measurement Cursor</item>
    </collection>   
    <primitives>
        <sl-prim>Sphere</sl-prim>
        <sl-prim>Box</sl-prim>
        <sl-prim>Cylinder</sl-prim>
    </primitives>
    <content>
        <sl-script>/scripts/SurveyingComputer.lsl</sl-script>
    </content>
</sl-object>

=== bogeo/sl-geovislab/inventory/objects/Voter.xml
<sl-object xsi:noNamespaceSchemaLocation="../../xsd/sl-object.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Simple Voter</title>
    <description>
        Simple voting system, sonsisting of a green, yellow, orange and red voter object.
    </description>
    <creator>
        <name>Benno Schmidt</name>
        <sl-id>BennoSchmidt</sl-id>
    </creator>
    <commands>
        <command>reset</command>
        <command>show</command>     
        <command>hide</command>
        <command>float</command>
        <command>nofloat</command>
        <command>list</command>
        <command>help</command>
    </commands>
    <collection>
        <item>Simple Voter - Green</item>
        <item>Simple Voter - Yellow</item>
        <item>Simple Voter - Orange</item>
        <item>Simple Voter - Red</item>
    </collection>   
    <primitives>
        <sl-prim>Prism</sl-prim>
        <sl-prim>Prism</sl-prim>
        <sl-prim>Prims</sl-prim>
    </primitives>
    <content>
        <sl-script>/scripts/Voter.lsl</sl-script>
    </content>
</sl-object>

=== bogeo/sl-geovislab/inventory/objects/MeasuringRod.xml
<sl-object xsi:noNamespaceSchemaLocation="../../xsd/sl-object.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>BSH - Measuring Rod MESH</title>
    <description>Messstab</description>
    <creator>
        <name>Matze Shinn</name>
        <sl-id>matze.shinn</sl-id>
    </creator>
    <purchase>
        <slm-description>BSH - Measuring Rod MESH</slm-description>
        <slm-seller>BSH Bauunternehmen Shinn &amp; Haalan</slm-seller>
        <slm-price>10</slm-price>
    </purchase>
</sl-object>

=== bogeo/sl-geovislab/inventory/objects/LandParcelInfo.xml
<sl-object xsi:noNamespaceSchemaLocation="../../xsd/sl-object.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 
    <title>LandParcelInfo</title>
    <description>Prvovide land parcel information for query position</description>
    <creator>
        <name>Benno Schmidt</name>
        <sl-id>BennoSchmidt</sl-id>
    </creator>
    <primitives>
        <sl-prim>Box</sl-prim>
    </primitives>
    <content>
        <sl-script>/scripts/LandParcelInfo.lsl</sl-script>
    </content>
</sl-object>
